services:
  - type: web
    name: tempting_wb
    env: python
    buildCommand: ""
    startCommand: gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tempting
          property: connectionString
      - key: SECRET_KEY
        generativeValue: true